### ISSUE TITLE
Quick actions don't work on ST

### ISSUE THREAD

**Issue by niquini** [YooSangBeom/Smartthings#4]
in smartthings when we click on the device and define the actions there, they do not work. Only if you create automations. It would be interesting if it worked because the process of creating is simpler. Is it possible to make this adjustment?

the attached print shows where the actions do not work

![2021-05-07 14 30 38](https://user-images.githubusercontent.com/9222292/117487000-d3bbcc80-af40-11eb-9f9d-e066d3e592cc.jpg)

**Comment by YooSangBeom** [comment]
I think it's a Smartthings application issue.
