### ISSUE TITLE
Zemismart 4 gang

### ISSUE THREAD

**Issue by davidfrat123** [YooSangBeom/Smartthings#5]
Hello. Thank you so much for writing the code!
However, the switch I have just received doesn't work with it. It seems the manufacturer and model are different to any in your code. 

manufacturer: _TZ3000_xabckq1v
model: TS004F

I have tried adding this to your code and failing miserably. So I was hoping you would be able to do it please?
Thank you, David.

**Comment by lexiismadd** [comment]
I also have the same model and manufacturer.
Would it be possible to add this one to your code?

**Comment by halfmooonn** [comment]
Since the Model have been changes(Even though the Shape is same)
There is a major error that ST Hub does not get a data from the "Zemismart 4 gang"
So in Korea We have a Custom guide that "Do not buy a switch Which has Model number TS004F
We are waiting for an update now..

**Comment by QKnoliver** [comment]
Same problem here bought 22 new buttons because I was verry happy with my 3 first buttons. Tried changing the data in original code but with no luck yet.

**Comment by QKnoliver** [comment]
Info off New button:
![8679ff61f5d8a356a532bc7be208b6729edb43e4_2_672x998](https://user-images.githubusercontent.com/81033656/120588021-b80bef00-c436-11eb-99d9-d1e7e200d142.png)


Info of old button:
![363aabe5c911c40f525d4ba91a9beec7fe5fcf4d_2_612x1000](https://user-images.githubusercontent.com/81033656/120588066-cc4fec00-c436-11eb-876e-8399d4ec3468.png)

**Comment by lexiismadd** [comment]
Im hoping that the developer has access to the correct data so they can update the code with the new stuff

**Comment by YooSangBeom** [comment]
Added support (TS004F).
Some functions are not supported (long press, double press)

**Comment by QKnoliver** [comment]
The Device gives no feedback when a button is pressed. not for one click, not for dubble click and not for long click.

**Comment by davidfrat123** [comment]
Thanks for changing the code. Smartthings recognises it as a Tuya Switch and you can assign the 4 buttons. But Unfortunately they don't do anything when clicked. It's like ST doesn't realise the button was pressed at all.

**Comment by QKnoliver** [comment]
> Thanks for changing the code. Smartthings recognises it as a Tuya Switch and you can assign the 4 buttons. But Unfortunately they don't do anything when clicked. It's like ST doesn't realise the button was pressed at all.

the code works. (only for one action per button) first you just need to give the buttons a purpose and then it will register every button (again only 1 press).

thanks for the code update!
